/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * AushadhiChakra healthcare supply resilience API
 * OpenAPI spec version: 0.1.0
 */
import type { CascadeRow } from './cascadeRow';

export interface CascadeSimulation {
  elasticity: number;
  displacement: number;
  spike: number;
  systemRisk: number;
  rows: CascadeRow[];
}
