/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * AushadhiChakra healthcare supply resilience API
 * OpenAPI spec version: 0.1.0
 */

export interface CascadeRow {
  facilityId: string;
  facilityName: string;
  drugName: string;
  originalBurnRate: number;
  cascadedBurnRate: number;
  updatedRunOutDays: number;
  shadowStockoutIndex: number;
  status: string;
}
