/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * AushadhiChakra healthcare supply resilience API
 * OpenAPI spec version: 0.1.0
 */

export type GetCascadeSimulationParams = {
/**
 * @minimum 0.5
 * @maximum 1
 */
elasticity?: number;
/**
 * @minimum 0.5
 * @maximum 1
 */
displacement?: number;
/**
 * @minimum 1
 * @maximum 3
 */
spike?: number;
};
