/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * AushadhiChakra healthcare supply resilience API
 * OpenAPI spec version: 0.1.0
 */

export interface InventoryItem {
  facilityId: string;
  facilityName: string;
  facilityType: string;
  drugCode: string;
  drugName: string;
  unit: string;
  currentUnits: number;
  dailyBurn: number;
  expiryDays: number;
  runOutDays: number;
  status: string;
  batchId: string;
}
