/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * AushadhiChakra healthcare supply resilience API
 * OpenAPI spec version: 0.1.0
 */
import type { NearestClinic } from './nearestClinic';
import type { TalukAvailability } from './talukAvailability';

export interface PublicAvailability {
  updatedAt: string;
  essentialMedicineAvailability: number;
  taluks: TalukAvailability[];
  nearestClinic: NearestClinic;
  advisory: string;
}
