/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * AushadhiChakra healthcare supply resilience API
 * OpenAPI spec version: 0.1.0
 */

export interface RebalanceOrder {
  id: string;
  donorId: string;
  donorName: string;
  recipientId: string;
  recipientName: string;
  drugCode: string;
  drugName: string;
  units: number;
  distanceKm: number;
  expiryDays: number;
  eta: string;
  carrier: string;
  status: string;
  authorizationCode: string;
  /** @nullable */
  batchId?: string | null;
}
